// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
double weighted_var_cpp(doubles x, doubles w);
extern "C" SEXP _wstats_weighted_var_cpp(SEXP x, SEXP w) {
  BEGIN_CPP11
    return cpp11::as_sexp(weighted_var_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<doubles>>(w)));
  END_CPP11
}
// code.cpp
double weighted_cov_cpp(doubles x, doubles y, doubles w);
extern "C" SEXP _wstats_weighted_cov_cpp(SEXP x, SEXP y, SEXP w) {
  BEGIN_CPP11
    return cpp11::as_sexp(weighted_cov_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<doubles>>(y), cpp11::as_cpp<cpp11::decay_t<doubles>>(w)));
  END_CPP11
}
// code.cpp
doubles weighted_quantile_cpp(doubles x, doubles w, doubles probs);
extern "C" SEXP _wstats_weighted_quantile_cpp(SEXP x, SEXP w, SEXP probs) {
  BEGIN_CPP11
    return cpp11::as_sexp(weighted_quantile_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<doubles>>(w), cpp11::as_cpp<cpp11::decay_t<doubles>>(probs)));
  END_CPP11
}
// code.cpp
double weighted_skewness_cpp(doubles x, doubles w);
extern "C" SEXP _wstats_weighted_skewness_cpp(SEXP x, SEXP w) {
  BEGIN_CPP11
    return cpp11::as_sexp(weighted_skewness_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<doubles>>(w)));
  END_CPP11
}
// code.cpp
double weighted_kurtosis_cpp(doubles x, doubles w);
extern "C" SEXP _wstats_weighted_kurtosis_cpp(SEXP x, SEXP w) {
  BEGIN_CPP11
    return cpp11::as_sexp(weighted_kurtosis_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<doubles>>(w)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_wstats_weighted_cov_cpp",      (DL_FUNC) &_wstats_weighted_cov_cpp,      3},
    {"_wstats_weighted_kurtosis_cpp", (DL_FUNC) &_wstats_weighted_kurtosis_cpp, 2},
    {"_wstats_weighted_quantile_cpp", (DL_FUNC) &_wstats_weighted_quantile_cpp, 3},
    {"_wstats_weighted_skewness_cpp", (DL_FUNC) &_wstats_weighted_skewness_cpp, 2},
    {"_wstats_weighted_var_cpp",      (DL_FUNC) &_wstats_weighted_var_cpp,      2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_wstats(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
