# Generated by cpp11: do not edit by hand

weighted_var_cpp <- function(x, w) {
  .Call(`_wstats_weighted_var_cpp`, x, w)
}

weighted_cov_cpp <- function(x, y, w) {
  .Call(`_wstats_weighted_cov_cpp`, x, y, w)
}

weighted_quantile_cpp <- function(x, w, probs) {
  .Call(`_wstats_weighted_quantile_cpp`, x, w, probs)
}

weighted_skewness_cpp <- function(x, w) {
  .Call(`_wstats_weighted_skewness_cpp`, x, w)
}

weighted_kurtosis_cpp <- function(x, w) {
  .Call(`_wstats_weighted_kurtosis_cpp`, x, w)
}
